/* This file is autogenerated, do not edit*/
#include "moc_exercise5.cpp"
#include "moc_exercise6.cpp"
#include "moc_mainwindow.cpp"
#include "moc_camera.cpp"
#include "moc_canvas.cpp"
#include "moc_glviewer.cpp"
#include "moc_navigation.cpp"
